apiVersion: apps/v1
kind: Deployment

metadata:
  name: chat
  namespace: streaming-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: chat

  template:
    metadata:
      labels:
        app: chat

    spec:
      containers:
        - name: chat
          image: gaurydocker/streaming-chat:1.0.0

          ports:
            - containerPort: 3004

          env:
            - name: PORT
              value: "3004"

            - name: MONGO_URI
              value: "mongodb://mongo:27017/streamingapp"

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: streaming-secret
                  key: JWT_SECRET

            - name: CLIENT_URLS
              valueFrom:
                configMapKeyRef:
                  name: streaming-config
                  key: CLIENT_URLS

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: streaming-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: streaming-secret
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: streaming-config
                  key: AWS_REGION