apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streaming-api-ingress
  namespace: streaming-app
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  ingressClassName: nginx
  rules:
    - host: streamingapp.local
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth
                port:
                  number: 3001

          - path: /api/streaming(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: streaming
                port:
                  number: 3002

          - path: /api/admin(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin
                port:
                  number: 3003

          - path: /api/chat(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: chat
                port:
                  number: 3004
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streaming-frontend-ingress
  namespace: streaming-app
spec:
  ingressClassName: nginx
  rules:
    - host: streamingapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80