apiVersion: v1
kind: Secret
metadata:
  name: streaming-secret
  namespace: streaming-app

type: Opaque

stringData:
  JWT_SECRET: "change-me-local"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""