apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.auth }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth
          image: "{{ .Values.images.auth.repository }}:{{ .Values.images.auth.tag }}"

          ports:
            - containerPort: 3001

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 20

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: streaming-config
                  key: AUTH_PORT

            - name: MONGO_URI
              value: {{ .Values.config.mongoUri | quote }}

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: streaming-secret
                  key: JWT_SECRET

            - name: CLIENT_URLS
              valueFrom:
                configMapKeyRef:
                  name: streaming-config
                  key: CLIENT_URLS

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: streaming-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: streaming-secret
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: streaming-config
                  key: AWS_REGION