apiVersion: v1
kind: Service
metadata:
  name: chat
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: chat

  ports:
    - name: http
      port: 3004
      targetPort: 3004

  type: ClusterIP