apiVersion: v1
kind: Secret
metadata:
  name: streaming-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsSecretAccessKey | quote }}